In [20]:
#importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [21]:
df = pd.read_csv('/content/gender_submission.csv')#importing the gender submission csv
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [22]:
test = pd.read_csv('/content/test.csv')#importing the test.csv file 
test

PassengerId  Pclass  ... Cabin Embarked
0            892       3  ...   NaN        Q
1            893       3  ...   NaN        S
2            894       2  ...   NaN        Q
3            895       3  ...   NaN        S
4            896       3  ...   NaN        S
..           ...     ...  ...   ...      ...
413         1305       3  ...   NaN        S
414         1306       1  ...  C105        C
415         1307       3  ...   NaN        S
416         1308       3  ...   NaN        S
417         1309       3  ...   NaN        C

[418 rows x 11 columns]

In [23]:
train = pd.read_csv('/content/train.csv')#importing the train.csv
train

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [24]:
train.info()#gathering the information about the

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [25]:
train = train.drop(['Name'],axis=1)#droping the name column as it contains the string values
test = test.drop(['Name'],axis=1)

In [26]:
def binary_map(x):
 return x.map({'male': 1, "female": 0})#maping the values of male and female 

In [27]:
train[['Sex']] = train[['Sex']].apply(binary_map)#using apply to map the values in 'sex' column in the data
test[['Sex']] = test[['Sex']].apply(binary_map)

In [28]:
train.info()#again verifying the information of table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    int64  
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(6), object(3)
memory usage: 76.7+ KB


In [29]:
train = train.drop(['Ticket','Cabin'],axis=1)#dropping the values of ticket and cabin as they are string and unique 
test = test.drop(['Ticket','Cabin'],axis=1)

In [30]:
train['Embarked'] = train['Embarked'].map({'S':1,'C':2,'Q':3})#mapping the values of S , C ,Q to convert it to float type
test['Embarked'] = test['Embarked'].map({'S':1,'C':2,'Q':3})

In [31]:
train['Age'].isnull().sum()#finding the number of null values in age column

177

In [32]:
train.fillna(train.mean() , inplace=True)#filling the null values in column with the mean values
test.fillna(test.mean(),inplace=True)

In [33]:
train

PassengerId  Survived  Pclass  Sex  ...  SibSp  Parch     Fare  Embarked
0              1         0       3    1  ...      1      0   7.2500       1.0
1              2         1       1    0  ...      1      0  71.2833       2.0
2              3         1       3    0  ...      0      0   7.9250       1.0
3              4         1       1    0  ...      1      0  53.1000       1.0
4              5         0       3    1  ...      0      0   8.0500       1.0
..           ...       ...     ...  ...  ...    ...    ...      ...       ...
886          887         0       2    1  ...      0      0  13.0000       1.0
887          888         1       1    0  ...      0      0  30.0000       1.0
888          889         0       3    0  ...      1      2  23.4500       1.0
889          890         1       1    1  ...      0      0  30.0000       2.0
890          891         0       3    1  ...      0      0   7.7500       3.0

[891 rows x 9 columns]

In [34]:
test

PassengerId  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0            892       3    1  34.50000      0      0    7.8292         3
1            893       3    0  47.00000      1      0    7.0000         1
2            894       2    1  62.00000      0      0    9.6875         3
3            895       3    1  27.00000      0      0    8.6625         1
4            896       3    0  22.00000      1      1   12.2875         1
..           ...     ...  ...       ...    ...    ...       ...       ...
413         1305       3    1  30.27259      0      0    8.0500         1
414         1306       1    0  39.00000      0      0  108.9000         2
415         1307       3    1  38.50000      0      0    7.2500         1
416         1308       3    1  30.27259      0      0    8.0500         1
417         1309       3    1  30.27259      1      1   22.3583         2

[418 rows x 8 columns]

In [35]:
x_train = train.iloc[:,2:].values  #creating x_variable for model(independent)
y_train = train.iloc[:,1:2].values #creating y_variable for model(dependent - 'Survived')

x_test = test.iloc[:,1:].values #creating x_test value for final prediction
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler() #scalar transformation to get all values in a range
x_train = sc.fit_transform(x_train)#fitting the transformation to x_train
x_test = sc.fit_transform(x_test)#fitting the transformation to x_test

In [36]:
print(x_train)

[[1.         1.         0.27117366 ... 0.         0.01415106 0.        ]
 [0.         0.         0.4722292  ... 0.         0.13913574 0.5       ]
 [1.         0.         0.32143755 ... 0.         0.01546857 0.        ]
 ...
 [1.         0.         0.36792055 ... 0.33333333 0.04577135 0.        ]
 [0.         1.         0.32143755 ... 0.         0.0585561  0.5       ]
 [1.         1.         0.39683338 ... 0.         0.01512699 1.        ]]


In [37]:
np.array(y_train)

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [38]:
from sklearn.linear_model import LogisticRegression#buildiing the model and applying the linear regression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)#fitting the model to data



/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [39]:
y_pred = classifier.predict(x_test)#predicting the values for x_test

In [40]:
y_pred #printing the values of y_prediction

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [41]:
y_test = df.iloc[:,1:2].values #taking the values from gender prediction for purpose of experiment

In [42]:
y_test #printing the values of y_test

array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [43]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))#concatinating both the y_pred and y_test
print(y_pred.shape)

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]

In [44]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
from sklearn.metrics import accuracy_score , f1_score , precision_score ,recall_score
ac = accuracy_score(y_pred,y_test) #finding the accuracy
f1 = f1_score(y_pred,y_test) #finding the f1 score
ps = precision_score(y_pred,y_test)#finding the precision score
rs = recall_score(y_pred,y_test)#finding the recall

print(ac)
print(f1)
print(ps)
print(rs)

[[255  11]
 [  8 144]]
0.9545454545454546
0.9381107491856677
0.9473684210526315
0.9290322580645162


In [45]:
d = {'PassengerId':df['PassengerId'],'Survived':y_pred}

In [46]:
result = pd.DataFrame(d)
result

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [47]:
 result.to_csv('result.csv',index=False)#converting the result into dataframe for kaggle

0.9545454545454546